FROM quay.io/thoth-station/s2i-minimal-py38-notebook:v0.1.1

USER root
COPY requirements.txt /requirements.txt
COPY requirements.notebook.txt /requirements.notebook.txt
RUN dnf install -y mesa-libGL; \
    pip install -r /requirements.txt; \
    pip install -r /requirements.notebook.txt
ENV JUPYTER_ENABLE_LAB=true
USER 1001
