FROM quay.io/thoth-station/s2i-minimal-notebook:v0.0.14

USER root
COPY requirements.txt /requirements.txt
COPY requirements.lab.txt /requirements.lab.txt
RUN dnf install -y mesa-libGL; \
    pip install -r /requirements.txt; \
    pip install -r /requirements.lab.txt
ENV JUPYTER_ENABLE_LAB=true
USER 1001
