apiVersion: v1
items:
- apiVersion: v1
  data:
    profile: |
      gpu: '0'
      last_selected_image: traffic-patterns-notebook-image:latest
      last_selected_size: Large
  kind: ConfigMap
  metadata:
    labels:
      app: jupyterhub
    name: jupyterhub-singleuser-profile-kube-3aadmin
- apiVersion: v1
  data:
    JUPYTER_PRELOAD_REPOS1: https://github.com/thehatrack/traffic-patterns
  kind: ConfigMap
  metadata:
    labels:
      app: jupyterhub
    name: jupyterhub-singleuser-profile-kube-3aadmin-envs
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
