apiVersion: v1
items:
- apiVersion: v1
  data:
    profile: |
      gpu: '0'
      last_selected_image: boat-demo-notebook-image:latest
      last_selected_size: Large
  kind: ConfigMap
  metadata:
    labels:
      app: jupyterhub
    name: jupyterhub-singleuser-profile-kubeadmin
- apiVersion: v1
  data:
    JUPYTER_PRELOAD_REPOS: https://github.com/redhat-naps-da/boat-demo.git
  kind: ConfigMap
  metadata:
    labels:
      app: jupyterhub
    name: jupyterhub-singleuser-profile-kubeadmin-envs
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
