apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
  - source:
      kind: Secret
      name: traffic-detection-modeling
      version: v1
    targets:
    - select:
        kind: Secret
        name: jupyterhub-singleuser-profile-kube-3aadmin-envs
      fieldPaths: data

resources:
  - odh.yaml
  - gpuconfigmap.yaml
  - kubeadmin-user-profile.yaml
