apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-patterns-opendatahub
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kustomize/opendatahub
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:                                                                         │[core@bastion ~]$
    automated: ~
